@API = http://localhost:3000/api/user
@DEVICE = http://localhost:3000/api/device
@TOKEN =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJKSlgtalZUSFp4Iiwicm9sZSI6InBvbGljZSIsImlhdCI6MTc0Njc4MDE2NCwiZXhwIjoxNzQ2ODIzMzY0fQ.ngfmsEqTM5MUtWchecx6jtNnBFndOZqq6UJfKQHLMxk
@USERNAME = TuongVi43
@PASSWORD = 2NzQCdn0yLHOduD

### Đăng ký
POST {{API}}/register
Content-Type: application/json

{
    "name": "Nguyễn Đức Bảo Lâm",
    "username" : "{{USERNAME}}",
    "password": "{{PASSWORD}}"
}

### Đăng nhập
POST {{API}}/login
Content-Type: application/json

{
    "username": "{{USERNAME}}",
    "password": "{{PASSWORD}}"
}

### Lấy toàn bộ thông tin
GET {{API}}/all
Authorization: Bearer {{TOKEN}}

### Lấy thông tin thiết bị
GET {{DEVICE}}/all/user
Authorization: Bearer {{TOKEN}}